# Generated by Django 3.0.3 on 2020-08-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='lon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='phone_number',
            field=models.IntegerField(default=463),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdistrict_name', models.CharField(max_length=64)),
                ('district_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_main.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_main.State'),
        ),
        migrations.AddField(
            model_name='apply',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apply_main.District'),
        ),
        migrations.AddField(
            model_name='apply',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apply_main.State'),
        ),
        migrations.AddField(
            model_name='apply',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apply_main.Subdistrict'),
        ),
    ]
