# Generated by Django 3.0.3 on 2020-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0003_auto_20200806_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
