# Generated by Django 3.0.3 on 2020-08-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0005_auto_20200806_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='state_f',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subdistrict',
            old_name='district_f',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='subdistrict',
            old_name='subdistrict_name',
            new_name='name',
        ),
    ]
