# Generated by Django 3.0.3 on 2020-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0006_auto_20200807_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='middle_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
