# Generated by Django 3.0.3 on 2020-08-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0010_auto_20200807_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='middle_name',
        ),
    ]
