# Generated by Django 3.0.3 on 2020-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0011_remove_apply_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='apply',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth (as on Aadhaar Card)'),
        ),
    ]
