# Generated by Django 3.0.3 on 2020-08-07 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0013_remove_apply_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='dob',
        ),
        migrations.AddField(
            model_name='apply',
            name='Date of Birth (as on Aadhaar Card)',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
