# Generated by Django 3.0.3 on 2020-08-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0014_auto_20200807_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Date of Birth (as on Aadhaar Card)',
            new_name='dob',
        ),
    ]
