# Generated by Django 3.0.3 on 2020-08-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0015_auto_20200807_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
