# Generated by Django 3.0.3 on 2020-08-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation_main', '0002_auto_20200805_1229'),
        ('apply_main', '0017_apply_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_main.Apply')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_main.Donate')),
            ],
        ),
    ]
