# Generated by Django 3.0.3 on 2020-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0018_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
