# Generated by Django 3.0.3 on 2020-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0019_auto_20200809_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='special_key',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
