# Generated by Django 3.0.3 on 2020-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0021_auto_20200810_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='request_sent',
            field=models.IntegerField(default=0),
        ),
    ]
