# Generated by Django 3.0.3 on 2020-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0009_auto_20200810_1114'),
        ('apply_main', '0022_auto_20200810_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.AlterField(
            model_name='apply',
            name='district',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='apply',
            name='state',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='apply',
            name='subdistrict',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Subdistrict',
        ),
    ]
