# Generated by Django 3.0.3 on 2020-08-13 04:32

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0024_apply_aadhaar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='aadhaar_image',
            field=smartfields.fields.ImageField(upload_to='aadhaar_image'),
        ),
    ]
