# Generated by Django 3.0.3 on 2020-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0025_auto_20200813_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='aadhaar_image',
            field=models.ImageField(blank=True, upload_to='aadhaar_image'),
        ),
    ]
