# Generated by Django 3.0.3 on 2020-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_main', '0005_auto_20200814_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='mobile_images',
            field=models.ImageField(blank=True, upload_to='donation_main'),
        ),
    ]
