# Generated by Django 3.0.3 on 2020-08-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply_main', '0016_auto_20200807_0814'),
        ('reg_sign_in_out', '0002_auto_20200721_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apply_main.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(default=2345346, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apply_main.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='subdistrict',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apply_main.Subdistrict'),
            preserve_default=False,
        ),
    ]
