# Generated by Django 3.0.3 on 2020-08-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0003_auto_20200807_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
