# Generated by Django 3.0.3 on 2020-08-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0004_delete_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='url',
        ),
    ]
