# Generated by Django 3.0.3 on 2020-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0006_registration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
