# Generated by Django 3.0.3 on 2020-08-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0007_auto_20200809_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
