# Generated by Django 3.0.3 on 2020-08-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0008_auto_20200810_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='subdistrict',
        ),
    ]
