# Generated by Django 3.0.3 on 2020-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0009_auto_20200810_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='district',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='subdistrict',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
