# Generated by Django 3.0.3 on 2020-08-14 04:45

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0011_auto_20200813_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_pic',
            field=smartfields.fields.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
